services:
  rapsodia:
    image: thieros/rapsodia-backend:${TAG:-latest}
    container_name: abitat_rapsodia_${ENV_NAME:-dev}
    restart: always
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENV:-Development}
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
    ports:
      - "${PORT:-10000}:10000"
    networks:
      - abitat_network

networks:
  abitat_network:
    external: true